root: true

env:
  node: true
  jest: true

extends: [airbnb, plugin:flowtype/recommended]

plugins:
  - react
  - jsx-a11y
  - import
  - flowtype

rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  import/no-extraneous-dependencies: ["error", {"devDependencies": true, "optionalDependencies": false, "peerDependencies": false}]
  no-underscore-dangle: ["error", { "allow": ["_id"] }]
  linebreak-style: [0, "unix"]
  react/forbid-prop-types: [0] #temp
  jsx-a11y/no-static-element-interactions: [0]
  arrow-parens: [0]
  react/jsx-wrap-multilines: [0]
  react/no-array-index-key: [0]

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true

globals:
  window: true
  fetch: true
  document: true
  location: true
  localStorage: true
  navigator: true
  URLSearchParams: true
  STATS: true
